# Generated by Django 5.2.8 on 2025-11-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=32)),
                ('domain_areas', models.TextField(blank=True)),
                ('programs', models.TextField(blank=True)),
                ('research_topics', models.TextField(blank=True)),
                ('methods_and_tech', models.TextField(blank=True)),
                ('affiliations_and_labs', models.TextField(blank=True)),
                ('typical_outputs', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('embedding', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
