# Generated by Django 5.2.8 on 2025-11-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='knn_edges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
