# Generated by Django 5.2.8 on 2025-11-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph_integration', '0002_faculty_cluster'),
        ('graph_integration', '0002_faculty_knn_edges'),
    ]

    operations = [
    ]
