# Generated by Django 5.2.8 on 2025-11-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_integration', '0003_merge_0002_faculty_cluster_0002_faculty_knn_edges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=64)),
                ('scope', models.CharField(blank=True, max_length=128)),
                ('mission', models.TextField(blank=True)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('core_activities', models.JSONField(blank=True, default=list)),
                ('flagship_projects', models.JSONField(blank=True, default=list)),
                ('target_members', models.CharField(blank=True, max_length=255)),
                ('affiliations', models.JSONField(blank=True, default=list)),
                ('partnerships', models.JSONField(blank=True, default=None, null=True)),
                ('skills_outcomes', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('social', models.JSONField(blank=True, default=None, null=True)),
                ('embedding', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
