# Generated by Django 5.2.8 on 2025-11-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_integration', '0004_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='cluster',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='knn_edges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
