# Generated by Django 5.2.8 on 2025-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
