# Generated by Django 5.2.8 on 2025-11-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_integration', '0002_student_messages_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='embedding',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
